wallpaper {
    monitor = 
    path = ~/.local/share/hypr-dotfiles/current/background
    fit_mode = cover
}

splash = false
ipc = true

# preload = ~/.local/share/hypr-dotfiles/current/background
# wallpaper = , ~/.local/share/hypr-dotfiles/current/background
# ipc = true
