wallpaper {
    monitor = eDP1
    path = ~/.local/share/dotfiles/current/background
    fit_mode = cover
}

#preload = ~/.local/share/dotfiles/current/background
#wallpaper = , ~/.local/share/dotfiles/current/background
#ipc = true
